/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as IntegracoesRouteImport } from './routes/integracoes'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrivacidadeExclusaoDeDadosRouteImport } from './routes/privacidade.exclusao-de-dados'
import { Route as IntegracoesRdRouteImport } from './routes/integracoes_.rd'
import { Route as HistoricoLeadIdRouteImport } from './routes/historico.$leadId'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedKanbanRouteImport } from './routes/_authenticated/kanban'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConversasRouteImport } from './routes/_authenticated/conversas'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings.index'
import { Route as AuthenticatedLeadsIndexRouteImport } from './routes/_authenticated/leads.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedSettingsUsersRouteImport } from './routes/_authenticated/settings.users'
import { Route as AuthenticatedSettingsTagsRouteImport } from './routes/_authenticated/settings.tags'
import { Route as AuthenticatedSettingsStagesRouteImport } from './routes/_authenticated/settings.stages'
import { Route as AuthenticatedSettingsHubRouteImport } from './routes/_authenticated/settings.hub'
import { Route as AuthenticatedSettingsEmpreendimentosRouteImport } from './routes/_authenticated/settings.empreendimentos'
import { Route as AuthenticatedSettingsCustomFieldsRouteImport } from './routes/_authenticated/settings.custom-fields'
import { Route as AuthenticatedLeadsNewRouteImport } from './routes/_authenticated/leads.new'
import { Route as AuthenticatedLeadsImportarRouteImport } from './routes/_authenticated/leads.importar'
import { Route as AuthenticatedLeadsIdRouteImport } from './routes/_authenticated/leads.$id'
import { Route as AuthenticatedConfiguracoesIntegracoesRouteImport } from './routes/_authenticated/configuracoes.integracoes'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminTagsRouteImport } from './routes/_authenticated/admin.tags'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin.notifications'
import { Route as AuthenticatedAdminFunnelRouteImport } from './routes/_authenticated/admin.funnel'
import { Route as AuthenticatedAdminEmpresasRouteImport } from './routes/_authenticated/admin.empresas'
import { Route as AuthenticatedAdminCustomFieldsRouteImport } from './routes/_authenticated/admin.custom-fields'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegracoesRoute = IntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeExclusaoDeDadosRoute =
  PrivacidadeExclusaoDeDadosRouteImport.update({
    id: '/privacidade/exclusao-de-dados',
    path: '/privacidade/exclusao-de-dados',
    getParentRoute: () => rootRouteImport,
  } as any)
const IntegracoesRdRoute = IntegracoesRdRouteImport.update({
  id: '/integracoes_/rd',
  path: '/integracoes/rd',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoLeadIdRoute = HistoricoLeadIdRouteImport.update({
  id: '/historico/$leadId',
  path: '/historico/$leadId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKanbanRoute = AuthenticatedKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConversasRoute = AuthenticatedConversasRouteImport.update({
  id: '/conversas',
  path: '/conversas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedLeadsIndexRoute = AuthenticatedLeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedSettingsUsersRoute =
  AuthenticatedSettingsUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsTagsRoute =
  AuthenticatedSettingsTagsRouteImport.update({
    id: '/tags',
    path: '/tags',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsStagesRoute =
  AuthenticatedSettingsStagesRouteImport.update({
    id: '/stages',
    path: '/stages',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsHubRoute =
  AuthenticatedSettingsHubRouteImport.update({
    id: '/hub',
    path: '/hub',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsEmpreendimentosRoute =
  AuthenticatedSettingsEmpreendimentosRouteImport.update({
    id: '/empreendimentos',
    path: '/empreendimentos',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsCustomFieldsRoute =
  AuthenticatedSettingsCustomFieldsRouteImport.update({
    id: '/custom-fields',
    path: '/custom-fields',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedLeadsNewRoute = AuthenticatedLeadsNewRouteImport.update({
  id: '/leads/new',
  path: '/leads/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsImportarRoute =
  AuthenticatedLeadsImportarRouteImport.update({
    id: '/leads/importar',
    path: '/leads/importar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeadsIdRoute = AuthenticatedLeadsIdRouteImport.update({
  id: '/leads/$id',
  path: '/leads/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesIntegracoesRoute =
  AuthenticatedConfiguracoesIntegracoesRouteImport.update({
    id: '/configuracoes/integracoes',
    path: '/configuracoes/integracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTagsRoute = AuthenticatedAdminTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFunnelRoute =
  AuthenticatedAdminFunnelRouteImport.update({
    id: '/funnel',
    path: '/funnel',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEmpresasRoute =
  AuthenticatedAdminEmpresasRouteImport.update({
    id: '/empresas',
    path: '/empresas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCustomFieldsRoute =
  AuthenticatedAdminCustomFieldsRouteImport.update({
    id: '/custom-fields',
    path: '/custom-fields',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/integracoes': typeof IntegracoesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/conversas': typeof AuthenticatedConversasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/kanban': typeof AuthenticatedKanbanRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/historico/$leadId': typeof HistoricoLeadIdRoute
  '/integracoes/rd': typeof IntegracoesRdRoute
  '/privacidade/exclusao-de-dados': typeof PrivacidadeExclusaoDeDadosRoute
  '/admin/custom-fields': typeof AuthenticatedAdminCustomFieldsRoute
  '/admin/empresas': typeof AuthenticatedAdminEmpresasRoute
  '/admin/funnel': typeof AuthenticatedAdminFunnelRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/tags': typeof AuthenticatedAdminTagsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/configuracoes/integracoes': typeof AuthenticatedConfiguracoesIntegracoesRoute
  '/leads/$id': typeof AuthenticatedLeadsIdRoute
  '/leads/importar': typeof AuthenticatedLeadsImportarRoute
  '/leads/new': typeof AuthenticatedLeadsNewRoute
  '/settings/custom-fields': typeof AuthenticatedSettingsCustomFieldsRoute
  '/settings/empreendimentos': typeof AuthenticatedSettingsEmpreendimentosRoute
  '/settings/hub': typeof AuthenticatedSettingsHubRoute
  '/settings/stages': typeof AuthenticatedSettingsStagesRoute
  '/settings/tags': typeof AuthenticatedSettingsTagsRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/leads/': typeof AuthenticatedLeadsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/integracoes': typeof IntegracoesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/conversas': typeof AuthenticatedConversasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/kanban': typeof AuthenticatedKanbanRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/historico/$leadId': typeof HistoricoLeadIdRoute
  '/integracoes/rd': typeof IntegracoesRdRoute
  '/privacidade/exclusao-de-dados': typeof PrivacidadeExclusaoDeDadosRoute
  '/admin/custom-fields': typeof AuthenticatedAdminCustomFieldsRoute
  '/admin/empresas': typeof AuthenticatedAdminEmpresasRoute
  '/admin/funnel': typeof AuthenticatedAdminFunnelRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/tags': typeof AuthenticatedAdminTagsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/configuracoes/integracoes': typeof AuthenticatedConfiguracoesIntegracoesRoute
  '/leads/$id': typeof AuthenticatedLeadsIdRoute
  '/leads/importar': typeof AuthenticatedLeadsImportarRoute
  '/leads/new': typeof AuthenticatedLeadsNewRoute
  '/settings/custom-fields': typeof AuthenticatedSettingsCustomFieldsRoute
  '/settings/empreendimentos': typeof AuthenticatedSettingsEmpreendimentosRoute
  '/settings/hub': typeof AuthenticatedSettingsHubRoute
  '/settings/stages': typeof AuthenticatedSettingsStagesRoute
  '/settings/tags': typeof AuthenticatedSettingsTagsRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/leads': typeof AuthenticatedLeadsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/integracoes': typeof IntegracoesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/conversas': typeof AuthenticatedConversasRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/kanban': typeof AuthenticatedKanbanRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/historico/$leadId': typeof HistoricoLeadIdRoute
  '/integracoes_/rd': typeof IntegracoesRdRoute
  '/privacidade/exclusao-de-dados': typeof PrivacidadeExclusaoDeDadosRoute
  '/_authenticated/admin/custom-fields': typeof AuthenticatedAdminCustomFieldsRoute
  '/_authenticated/admin/empresas': typeof AuthenticatedAdminEmpresasRoute
  '/_authenticated/admin/funnel': typeof AuthenticatedAdminFunnelRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/tags': typeof AuthenticatedAdminTagsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/configuracoes/integracoes': typeof AuthenticatedConfiguracoesIntegracoesRoute
  '/_authenticated/leads/$id': typeof AuthenticatedLeadsIdRoute
  '/_authenticated/leads/importar': typeof AuthenticatedLeadsImportarRoute
  '/_authenticated/leads/new': typeof AuthenticatedLeadsNewRoute
  '/_authenticated/settings/custom-fields': typeof AuthenticatedSettingsCustomFieldsRoute
  '/_authenticated/settings/empreendimentos': typeof AuthenticatedSettingsEmpreendimentosRoute
  '/_authenticated/settings/hub': typeof AuthenticatedSettingsHubRoute
  '/_authenticated/settings/stages': typeof AuthenticatedSettingsStagesRoute
  '/_authenticated/settings/tags': typeof AuthenticatedSettingsTagsRoute
  '/_authenticated/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/leads/': typeof AuthenticatedLeadsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/integracoes'
    | '/reset-password'
    | '/setup'
    | '/admin'
    | '/conversas'
    | '/dashboard'
    | '/kanban'
    | '/profile'
    | '/relatorios'
    | '/settings'
    | '/historico/$leadId'
    | '/integracoes/rd'
    | '/privacidade/exclusao-de-dados'
    | '/admin/custom-fields'
    | '/admin/empresas'
    | '/admin/funnel'
    | '/admin/notifications'
    | '/admin/tags'
    | '/admin/users'
    | '/configuracoes/integracoes'
    | '/leads/$id'
    | '/leads/importar'
    | '/leads/new'
    | '/settings/custom-fields'
    | '/settings/empreendimentos'
    | '/settings/hub'
    | '/settings/stages'
    | '/settings/tags'
    | '/settings/users'
    | '/admin/'
    | '/leads/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/integracoes'
    | '/reset-password'
    | '/setup'
    | '/conversas'
    | '/dashboard'
    | '/kanban'
    | '/profile'
    | '/relatorios'
    | '/historico/$leadId'
    | '/integracoes/rd'
    | '/privacidade/exclusao-de-dados'
    | '/admin/custom-fields'
    | '/admin/empresas'
    | '/admin/funnel'
    | '/admin/notifications'
    | '/admin/tags'
    | '/admin/users'
    | '/configuracoes/integracoes'
    | '/leads/$id'
    | '/leads/importar'
    | '/leads/new'
    | '/settings/custom-fields'
    | '/settings/empreendimentos'
    | '/settings/hub'
    | '/settings/stages'
    | '/settings/tags'
    | '/settings/users'
    | '/admin'
    | '/leads'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/integracoes'
    | '/reset-password'
    | '/setup'
    | '/_authenticated/admin'
    | '/_authenticated/conversas'
    | '/_authenticated/dashboard'
    | '/_authenticated/kanban'
    | '/_authenticated/profile'
    | '/_authenticated/relatorios'
    | '/_authenticated/settings'
    | '/historico/$leadId'
    | '/integracoes_/rd'
    | '/privacidade/exclusao-de-dados'
    | '/_authenticated/admin/custom-fields'
    | '/_authenticated/admin/empresas'
    | '/_authenticated/admin/funnel'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/tags'
    | '/_authenticated/admin/users'
    | '/_authenticated/configuracoes/integracoes'
    | '/_authenticated/leads/$id'
    | '/_authenticated/leads/importar'
    | '/_authenticated/leads/new'
    | '/_authenticated/settings/custom-fields'
    | '/_authenticated/settings/empreendimentos'
    | '/_authenticated/settings/hub'
    | '/_authenticated/settings/stages'
    | '/_authenticated/settings/tags'
    | '/_authenticated/settings/users'
    | '/_authenticated/admin/'
    | '/_authenticated/leads/'
    | '/_authenticated/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  IntegracoesRoute: typeof IntegracoesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetupRoute: typeof SetupRoute
  HistoricoLeadIdRoute: typeof HistoricoLeadIdRoute
  IntegracoesRdRoute: typeof IntegracoesRdRoute
  PrivacidadeExclusaoDeDadosRoute: typeof PrivacidadeExclusaoDeDadosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integracoes': {
      id: '/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof IntegracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade/exclusao-de-dados': {
      id: '/privacidade/exclusao-de-dados'
      path: '/privacidade/exclusao-de-dados'
      fullPath: '/privacidade/exclusao-de-dados'
      preLoaderRoute: typeof PrivacidadeExclusaoDeDadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integracoes_/rd': {
      id: '/integracoes_/rd'
      path: '/integracoes/rd'
      fullPath: '/integracoes/rd'
      preLoaderRoute: typeof IntegracoesRdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico/$leadId': {
      id: '/historico/$leadId'
      path: '/historico/$leadId'
      fullPath: '/historico/$leadId'
      preLoaderRoute: typeof HistoricoLeadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kanban': {
      id: '/_authenticated/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof AuthenticatedKanbanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conversas': {
      id: '/_authenticated/conversas'
      path: '/conversas'
      fullPath: '/conversas'
      preLoaderRoute: typeof AuthenticatedConversasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/leads/': {
      id: '/_authenticated/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof AuthenticatedLeadsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/settings/users': {
      id: '/_authenticated/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AuthenticatedSettingsUsersRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/tags': {
      id: '/_authenticated/settings/tags'
      path: '/tags'
      fullPath: '/settings/tags'
      preLoaderRoute: typeof AuthenticatedSettingsTagsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/stages': {
      id: '/_authenticated/settings/stages'
      path: '/stages'
      fullPath: '/settings/stages'
      preLoaderRoute: typeof AuthenticatedSettingsStagesRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/hub': {
      id: '/_authenticated/settings/hub'
      path: '/hub'
      fullPath: '/settings/hub'
      preLoaderRoute: typeof AuthenticatedSettingsHubRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/empreendimentos': {
      id: '/_authenticated/settings/empreendimentos'
      path: '/empreendimentos'
      fullPath: '/settings/empreendimentos'
      preLoaderRoute: typeof AuthenticatedSettingsEmpreendimentosRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/custom-fields': {
      id: '/_authenticated/settings/custom-fields'
      path: '/custom-fields'
      fullPath: '/settings/custom-fields'
      preLoaderRoute: typeof AuthenticatedSettingsCustomFieldsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/leads/new': {
      id: '/_authenticated/leads/new'
      path: '/leads/new'
      fullPath: '/leads/new'
      preLoaderRoute: typeof AuthenticatedLeadsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads/importar': {
      id: '/_authenticated/leads/importar'
      path: '/leads/importar'
      fullPath: '/leads/importar'
      preLoaderRoute: typeof AuthenticatedLeadsImportarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads/$id': {
      id: '/_authenticated/leads/$id'
      path: '/leads/$id'
      fullPath: '/leads/$id'
      preLoaderRoute: typeof AuthenticatedLeadsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes/integracoes': {
      id: '/_authenticated/configuracoes/integracoes'
      path: '/configuracoes/integracoes'
      fullPath: '/configuracoes/integracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesIntegracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tags': {
      id: '/_authenticated/admin/tags'
      path: '/tags'
      fullPath: '/admin/tags'
      preLoaderRoute: typeof AuthenticatedAdminTagsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/funnel': {
      id: '/_authenticated/admin/funnel'
      path: '/funnel'
      fullPath: '/admin/funnel'
      preLoaderRoute: typeof AuthenticatedAdminFunnelRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/empresas': {
      id: '/_authenticated/admin/empresas'
      path: '/empresas'
      fullPath: '/admin/empresas'
      preLoaderRoute: typeof AuthenticatedAdminEmpresasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/custom-fields': {
      id: '/_authenticated/admin/custom-fields'
      path: '/custom-fields'
      fullPath: '/admin/custom-fields'
      preLoaderRoute: typeof AuthenticatedAdminCustomFieldsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCustomFieldsRoute: typeof AuthenticatedAdminCustomFieldsRoute
  AuthenticatedAdminEmpresasRoute: typeof AuthenticatedAdminEmpresasRoute
  AuthenticatedAdminFunnelRoute: typeof AuthenticatedAdminFunnelRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminTagsRoute: typeof AuthenticatedAdminTagsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCustomFieldsRoute: AuthenticatedAdminCustomFieldsRoute,
  AuthenticatedAdminEmpresasRoute: AuthenticatedAdminEmpresasRoute,
  AuthenticatedAdminFunnelRoute: AuthenticatedAdminFunnelRoute,
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedAdminTagsRoute: AuthenticatedAdminTagsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsCustomFieldsRoute: typeof AuthenticatedSettingsCustomFieldsRoute
  AuthenticatedSettingsEmpreendimentosRoute: typeof AuthenticatedSettingsEmpreendimentosRoute
  AuthenticatedSettingsHubRoute: typeof AuthenticatedSettingsHubRoute
  AuthenticatedSettingsStagesRoute: typeof AuthenticatedSettingsStagesRoute
  AuthenticatedSettingsTagsRoute: typeof AuthenticatedSettingsTagsRoute
  AuthenticatedSettingsUsersRoute: typeof AuthenticatedSettingsUsersRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsCustomFieldsRoute:
    AuthenticatedSettingsCustomFieldsRoute,
  AuthenticatedSettingsEmpreendimentosRoute:
    AuthenticatedSettingsEmpreendimentosRoute,
  AuthenticatedSettingsHubRoute: AuthenticatedSettingsHubRoute,
  AuthenticatedSettingsStagesRoute: AuthenticatedSettingsStagesRoute,
  AuthenticatedSettingsTagsRoute: AuthenticatedSettingsTagsRoute,
  AuthenticatedSettingsUsersRoute: AuthenticatedSettingsUsersRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedConversasRoute: typeof AuthenticatedConversasRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedKanbanRoute: typeof AuthenticatedKanbanRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedConfiguracoesIntegracoesRoute: typeof AuthenticatedConfiguracoesIntegracoesRoute
  AuthenticatedLeadsIdRoute: typeof AuthenticatedLeadsIdRoute
  AuthenticatedLeadsImportarRoute: typeof AuthenticatedLeadsImportarRoute
  AuthenticatedLeadsNewRoute: typeof AuthenticatedLeadsNewRoute
  AuthenticatedLeadsIndexRoute: typeof AuthenticatedLeadsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedConversasRoute: AuthenticatedConversasRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedKanbanRoute: AuthenticatedKanbanRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedConfiguracoesIntegracoesRoute:
    AuthenticatedConfiguracoesIntegracoesRoute,
  AuthenticatedLeadsIdRoute: AuthenticatedLeadsIdRoute,
  AuthenticatedLeadsImportarRoute: AuthenticatedLeadsImportarRoute,
  AuthenticatedLeadsNewRoute: AuthenticatedLeadsNewRoute,
  AuthenticatedLeadsIndexRoute: AuthenticatedLeadsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  IntegracoesRoute: IntegracoesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetupRoute: SetupRoute,
  HistoricoLeadIdRoute: HistoricoLeadIdRoute,
  IntegracoesRdRoute: IntegracoesRdRoute,
  PrivacidadeExclusaoDeDadosRoute: PrivacidadeExclusaoDeDadosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
