create table public.followup_completion_policies_v2 (
  id bigint generated by default as identity primary key,
  sequence_id bigint not null references public.followup_sequences_v2(id) on delete cascade,
  enabled boolean not null default false,
  qualified_enabled boolean not null default false,
  qualified_mark_as_lost boolean not null default false,
  qualified_send_to_queue boolean not null default false,
  qualified_queue_id text,
  qualified_tags text[] not null default '{}'::text[],
  unqualified_enabled boolean not null default false,
  unqualified_mark_as_lost boolean not null default true,
  unqualified_send_to_queue boolean not null default false,
  unqualified_queue_id text,
  unqualified_tags text[] not null default '{}'::text[],
  cancellation_reason_id text,
  cancellation_reason_name text,
  dispatch_delay_minutes integer not null default 0,
  max_attempts smallint not null default 3,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint followup_completion_policies_v2_sequence_uidx unique (sequence_id),
  constraint followup_completion_policies_v2_delay_check
    check (dispatch_delay_minutes between 0 and 10080),
  constraint followup_completion_policies_v2_attempts_check
    check (max_attempts between 1 and 10),
  constraint followup_completion_policies_v2_qualified_queue_check
    check (
      not enabled
      or not qualified_enabled
      or not qualified_send_to_queue
      or nullif(btrim(qualified_queue_id), '') is not null
    ),
  constraint followup_completion_policies_v2_unqualified_queue_check
    check (
      not enabled
      or not unqualified_enabled
      or not unqualified_send_to_queue
      or nullif(btrim(unqualified_queue_id), '') is not null
    )
);

create index followup_completion_policies_v2_enabled_idx
  on public.followup_completion_policies_v2 (sequence_id)
  where enabled;

create trigger followup_completion_policies_v2_set_updated_at
before update on public.followup_completion_policies_v2
for each row execute function public.handle_updated_at();

create table public.followup_completion_events_v2 (
  id bigint generated by default as identity primary key,
  policy_id bigint not null references public.followup_completion_policies_v2(id) on delete restrict,
  sequence_id bigint not null references public.followup_sequences_v2(id) on delete restrict,
  enrollment_id bigint references public.followup_enrollments_v2(id) on delete set null,
  final_dispatch_id bigint not null references public.followup_dispatches_v2(id) on delete restrict,
  lead_id bigint not null references public.lead(id) on delete restrict,
  id_empresa bigint not null references public.empresa_dados(id) on delete restrict,
  classification text not null,
  status text not null default 'pending',
  scheduled_at timestamptz not null default now(),
  attempts smallint not null default 0,
  max_attempts smallint not null default 3,
  claimed_at timestamptz,
  claimed_by text,
  processed_at timestamptz,
  last_error text,
  payload_snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint followup_completion_events_v2_dispatch_uidx unique (final_dispatch_id),
  constraint followup_completion_events_v2_classification_check
    check (classification in ('qualified', 'unqualified')),
  constraint followup_completion_events_v2_status_check
    check (status in ('pending', 'processing', 'succeeded', 'dead')),
  constraint followup_completion_events_v2_attempts_check
    check (attempts >= 0 and max_attempts between 1 and 10)
);

create index followup_completion_events_v2_claim_idx
  on public.followup_completion_events_v2 (scheduled_at, id)
  where status = 'pending';

create index followup_completion_events_v2_company_lead_idx
  on public.followup_completion_events_v2 (id_empresa, lead_id, created_at desc);

create trigger followup_completion_events_v2_set_updated_at
before update on public.followup_completion_events_v2
for each row execute function public.handle_updated_at();

alter table public.followup_completion_policies_v2 enable row level security;
alter table public.followup_completion_events_v2 enable row level security;

revoke all on table public.followup_completion_policies_v2 from anon, authenticated;
revoke all on table public.followup_completion_events_v2 from anon, authenticated;
grant select, insert, update, delete on table public.followup_completion_policies_v2 to service_role;
grant select, insert, update, delete on table public.followup_completion_events_v2 to service_role;
grant usage, select on sequence public.followup_completion_policies_v2_id_seq to service_role;
grant usage, select on sequence public.followup_completion_events_v2_id_seq to service_role;

create or replace function public.claim_followup_completion_events_v2(
  p_worker_id text,
  p_limit integer default 10
)
returns setof public.followup_completion_events_v2
language plpgsql
set search_path to ''
as $function$
begin
  if nullif(btrim(p_worker_id), '') is null then
    raise exception 'worker_id is required';
  end if;

  return query
  with candidates as (
    select e.id
    from public.followup_completion_events_v2 e
    where e.scheduled_at <= now()
      and e.attempts < e.max_attempts
      and (
        e.status = 'pending'
        or (e.status = 'processing' and e.claimed_at < now() - interval '15 minutes')
      )
    order by e.scheduled_at, e.id
    for update skip locked
    limit greatest(1, least(coalesce(p_limit, 10), 100))
  )
  update public.followup_completion_events_v2 e
     set status = 'processing',
         claimed_at = now(),
         claimed_by = btrim(p_worker_id),
         attempts = e.attempts + 1,
         updated_at = now()
    from candidates c
   where e.id = c.id
  returning e.*;
end;
$function$;

create or replace function public.complete_followup_completion_event_v2(
  p_event_id bigint,
  p_worker_id text,
  p_success boolean,
  p_error text default null,
  p_retryable boolean default true
)
returns jsonb
language plpgsql
set search_path to ''
as $function$
declare
  v_event public.followup_completion_events_v2%rowtype;
  v_next_status text;
begin
  select * into v_event
  from public.followup_completion_events_v2 e
  where e.id = p_event_id
  for update;

  if not found then
    return jsonb_build_object('updated', false, 'reason', 'event_not_found');
  end if;

  if v_event.status <> 'processing' or v_event.claimed_by is distinct from btrim(p_worker_id) then
    return jsonb_build_object('updated', false, 'reason', 'event_not_owned');
  end if;

  v_next_status := case
    when p_success then 'succeeded'
    when p_retryable and v_event.attempts < v_event.max_attempts then 'pending'
    else 'dead'
  end;

  update public.followup_completion_events_v2
     set status = v_next_status,
         scheduled_at = case
           when v_next_status = 'pending'
             then now() + make_interval(mins => least(60, (5 * power(2, greatest(v_event.attempts - 1, 0)))::integer))
           else scheduled_at
         end,
         processed_at = case when v_next_status in ('succeeded', 'dead') then now() else null end,
         last_error = case when p_success then null else left(coalesce(p_error, 'Falha sem detalhes.'), 5000) end,
         claimed_at = null,
         claimed_by = null,
         updated_at = now()
   where id = p_event_id;

  return jsonb_build_object(
    'updated', true,
    'event_id', p_event_id,
    'status', v_next_status,
    'attempts', v_event.attempts,
    'max_attempts', v_event.max_attempts
  );
end;
$function$;

revoke all on function public.claim_followup_completion_events_v2(text, integer) from public, anon, authenticated;
revoke all on function public.complete_followup_completion_event_v2(bigint, text, boolean, text, boolean) from public, anon, authenticated;
grant execute on function public.claim_followup_completion_events_v2(text, integer) to service_role;
grant execute on function public.complete_followup_completion_event_v2(bigint, text, boolean, text, boolean) to service_role;

create or replace function public.accept_followup_attempt_v2(
  p_attempt_id bigint,
  p_meta_message_id text,
  p_meta_response jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
set search_path to ''
as $function$
declare
  v_attempt public.followup_attempts_v2%rowtype;
  v_dispatch public.followup_dispatches_v2%rowtype;
  v_next_step integer;
  v_policy public.followup_completion_policies_v2%rowtype;
  v_lead public.lead%rowtype;
  v_classification text;
  v_action_enabled boolean;
  v_mark_as_lost boolean;
  v_send_to_queue boolean;
  v_queue_id text;
  v_tags text[];
  v_event_id bigint;
  v_current_step_order integer;
  v_current_step_situation bigint;
begin
  if nullif(btrim(p_meta_message_id), '') is null then
    raise exception 'meta_message_id is required';
  end if;

  select * into v_attempt
  from public.followup_attempts_v2 a
  where a.id = p_attempt_id
  for update;

  if not found then
    return jsonb_build_object('accepted', false, 'reason', 'attempt_not_found');
  end if;

  if v_attempt.status <> 'preparing' then
    return jsonb_build_object(
      'accepted', false,
      'reason', 'attempt_not_preparing',
      'status', v_attempt.status
    );
  end if;

  select * into v_dispatch
  from public.followup_dispatches_v2 d
  where d.id = v_attempt.dispatch_id
  for update;

  update public.wa_messages
     set message_id = p_meta_message_id,
         status_current = 'accepted',
         status_last_at = now(),
         raw = coalesce(raw, '{}'::jsonb) || jsonb_build_object('meta_response', coalesce(p_meta_response, '{}'::jsonb)),
         updated_at = now()
   where id = v_attempt.wa_message_id;

  update public.followup_attempts_v2
     set meta_message_id = p_meta_message_id,
         status = 'accepted',
         accepted_at = now(),
         meta_response = coalesce(p_meta_response, '{}'::jsonb),
         updated_at = now()
   where id = p_attempt_id;

  update public.followup_dispatches_v2
     set status = 'accepted',
         sent_to_meta_at = now(),
         updated_at = now()
   where id = v_dispatch.id;

  select st.step_order, st.id_situacao
    into v_current_step_order, v_current_step_situation
  from public.followup_steps_v2 st
  where st.id = v_dispatch.step_id;

  select min(st.step_order)
    into v_next_step
  from public.followup_steps_v2 st
  where st.sequence_id = v_dispatch.sequence_id
    and st.is_active = true
    and st.step_order > v_current_step_order;

  if v_next_step is null then
    update public.followup_enrollments_v2
       set status = 'completed',
           completed_at = now(),
           last_evaluated_at = now(),
           updated_at = now()
     where id = v_dispatch.enrollment_id;

    select * into v_policy
    from public.followup_completion_policies_v2 p
    where p.sequence_id = v_dispatch.sequence_id
      and p.enabled = true;

    if found then
      select * into v_lead
      from public.lead l
      where l.id = v_dispatch.lead_id;

      v_classification := case when coalesce(v_lead.qualificado, 0) = 1 then 'qualified' else 'unqualified' end;

      if v_classification = 'qualified' then
        v_action_enabled := v_policy.qualified_enabled;
        v_mark_as_lost := v_policy.qualified_mark_as_lost;
        v_send_to_queue := v_policy.qualified_send_to_queue;
        v_queue_id := nullif(btrim(v_policy.qualified_queue_id), '');
        v_tags := v_policy.qualified_tags;
      else
        v_action_enabled := v_policy.unqualified_enabled;
        v_mark_as_lost := v_policy.unqualified_mark_as_lost;
        v_send_to_queue := v_policy.unqualified_send_to_queue;
        v_queue_id := nullif(btrim(v_policy.unqualified_queue_id), '');
        v_tags := v_policy.unqualified_tags;
      end if;

      if v_action_enabled then
        insert into public.followup_completion_events_v2 (
          policy_id,
          sequence_id,
          enrollment_id,
          final_dispatch_id,
          lead_id,
          id_empresa,
          classification,
          scheduled_at,
          max_attempts,
          payload_snapshot
        ) values (
          v_policy.id,
          v_dispatch.sequence_id,
          v_dispatch.enrollment_id,
          v_dispatch.id,
          v_dispatch.lead_id,
          v_dispatch.id_empresa,
          v_classification,
          now() + make_interval(mins => v_policy.dispatch_delay_minutes),
          v_policy.max_attempts,
          jsonb_build_object(
            'classification', v_classification,
            'mark_as_lost', v_mark_as_lost,
            'send_to_queue', v_send_to_queue,
            'queue_id', v_queue_id,
            'additional_tags', to_jsonb(coalesce(v_tags, '{}'::text[])),
            'cancellation_reason_id', nullif(btrim(v_policy.cancellation_reason_id), ''),
            'cancellation_reason_name', nullif(btrim(v_policy.cancellation_reason_name), ''),
            'id_empreendimento', v_dispatch.id_empreendimento,
            'final_step_id', v_dispatch.step_id,
            'final_step_order', v_current_step_order,
            'final_step_situation_id', v_current_step_situation
          )
        )
        on conflict (final_dispatch_id) do nothing
        returning id into v_event_id;
      end if;
    end if;
  else
    update public.followup_enrollments_v2
       set next_step_order = v_next_step,
           last_evaluated_at = now(),
           updated_at = now()
     where id = v_dispatch.enrollment_id;
  end if;

  update public.lead
     set etapa_conversa = coalesce(v_next_step, etapa_conversa + 1),
         ult_message = now()::text,
         updated_at = now()
   where id = v_dispatch.lead_id;

  return jsonb_build_object(
    'accepted', true,
    'attempt_id', p_attempt_id,
    'dispatch_id', v_dispatch.id,
    'meta_message_id', p_meta_message_id,
    'next_step_order', v_next_step,
    'enrollment_completed', v_next_step is null,
    'completion_event_id', v_event_id
  );
end;
$function$;

revoke all on function public.accept_followup_attempt_v2(bigint, text, jsonb) from public, anon, authenticated;
grant execute on function public.accept_followup_attempt_v2(bigint, text, jsonb) to service_role;

comment on table public.followup_completion_policies_v2 is
  'Optional per-cadence actions executed after the last active follow-up step. No row means no extra action.';
comment on table public.followup_completion_events_v2 is
  'Idempotent queue of terminal follow-up actions, with one event per final dispatch.';
